// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "kubebuilder-demo/pkg/apis/mammals/v1beta1"
	"kubebuilder-demo/pkg/client/clientset/versioned/scheme"

	serializer "k8s.io/apimachinery/pkg/runtime/serializer"
	rest "k8s.io/client-go/rest"
)

type MammalsV1beta1Interface interface {
	RESTClient() rest.Interface
	SlothsGetter
}

// MammalsV1beta1Client is used to interact with features provided by the mammals.chill.af group.
type MammalsV1beta1Client struct {
	restClient rest.Interface
}

func (c *MammalsV1beta1Client) Sloths(namespace string) SlothInterface {
	return newSloths(c, namespace)
}

// NewForConfig creates a new MammalsV1beta1Client for the given config.
func NewForConfig(c *rest.Config) (*MammalsV1beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &MammalsV1beta1Client{client}, nil
}

// NewForConfigOrDie creates a new MammalsV1beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *MammalsV1beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new MammalsV1beta1Client for the given RESTClient.
func New(c rest.Interface) *MammalsV1beta1Client {
	return &MammalsV1beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *MammalsV1beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
