// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "kubebuilder-demo/pkg/apis/mammals/v1beta1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSloths implements SlothInterface
type FakeSloths struct {
	Fake *FakeMammalsV1beta1
	ns   string
}

var slothsResource = schema.GroupVersionResource{Group: "mammals.chill.af", Version: "v1beta1", Resource: "sloths"}

var slothsKind = schema.GroupVersionKind{Group: "mammals.chill.af", Version: "v1beta1", Kind: "Sloth"}

// Get takes name of the sloth, and returns the corresponding sloth object, and an error if there is any.
func (c *FakeSloths) Get(name string, options v1.GetOptions) (result *v1beta1.Sloth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(slothsResource, c.ns, name), &v1beta1.Sloth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Sloth), err
}

// List takes label and field selectors, and returns the list of Sloths that match those selectors.
func (c *FakeSloths) List(opts v1.ListOptions) (result *v1beta1.SlothList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(slothsResource, slothsKind, c.ns, opts), &v1beta1.SlothList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.SlothList{}
	for _, item := range obj.(*v1beta1.SlothList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sloths.
func (c *FakeSloths) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(slothsResource, c.ns, opts))

}

// Create takes the representation of a sloth and creates it.  Returns the server's representation of the sloth, and an error, if there is any.
func (c *FakeSloths) Create(sloth *v1beta1.Sloth) (result *v1beta1.Sloth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(slothsResource, c.ns, sloth), &v1beta1.Sloth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Sloth), err
}

// Update takes the representation of a sloth and updates it. Returns the server's representation of the sloth, and an error, if there is any.
func (c *FakeSloths) Update(sloth *v1beta1.Sloth) (result *v1beta1.Sloth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(slothsResource, c.ns, sloth), &v1beta1.Sloth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Sloth), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSloths) UpdateStatus(sloth *v1beta1.Sloth) (*v1beta1.Sloth, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(slothsResource, "status", c.ns, sloth), &v1beta1.Sloth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Sloth), err
}

// Delete takes name of the sloth and deletes it. Returns an error if one occurs.
func (c *FakeSloths) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(slothsResource, c.ns, name), &v1beta1.Sloth{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSloths) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(slothsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.SlothList{})
	return err
}

// Patch applies the patch and returns the patched sloth.
func (c *FakeSloths) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Sloth, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(slothsResource, c.ns, name, data, subresources...), &v1beta1.Sloth{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.Sloth), err
}
