// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// SlothListerExpansion allows custom methods to be added to
// SlothLister.
type SlothListerExpansion interface{}

// SlothNamespaceListerExpansion allows custom methods to be added to
// SlothNamespaceLister.
type SlothNamespaceListerExpansion interface{}
