// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	mammals_v1beta1 "kubebuilder-demo/pkg/apis/mammals/v1beta1"
	versioned "kubebuilder-demo/pkg/client/clientset/versioned"
	internalinterfaces "kubebuilder-demo/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "kubebuilder-demo/pkg/client/listers/mammals/v1beta1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SlothInformer provides access to a shared informer and lister for
// Sloths.
type SlothInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.SlothLister
}

type slothInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSlothInformer constructs a new informer for Sloth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSlothInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSlothInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSlothInformer constructs a new informer for Sloth type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSlothInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MammalsV1beta1().Sloths(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MammalsV1beta1().Sloths(namespace).Watch(options)
			},
		},
		&mammals_v1beta1.Sloth{},
		resyncPeriod,
		indexers,
	)
}

func (f *slothInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSlothInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *slothInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mammals_v1beta1.Sloth{}, f.defaultInformer)
}

func (f *slothInformer) Lister() v1beta1.SlothLister {
	return v1beta1.NewSlothLister(f.Informer().GetIndexer())
}
