// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	mammalsv1beta1 "kubebuilder-demo/pkg/client/clientset/versioned/typed/mammals/v1beta1"

	glog "github.com/golang/glog"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	MammalsV1beta1() mammalsv1beta1.MammalsV1beta1Interface
	// Deprecated: please explicitly pick a version if possible.
	Mammals() mammalsv1beta1.MammalsV1beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	mammalsV1beta1 *mammalsv1beta1.MammalsV1beta1Client
}

// MammalsV1beta1 retrieves the MammalsV1beta1Client
func (c *Clientset) MammalsV1beta1() mammalsv1beta1.MammalsV1beta1Interface {
	return c.mammalsV1beta1
}

// Deprecated: Mammals retrieves the default version of MammalsClient.
// Please explicitly pick a version.
func (c *Clientset) Mammals() mammalsv1beta1.MammalsV1beta1Interface {
	return c.mammalsV1beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.mammalsV1beta1, err = mammalsv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		glog.Errorf("failed to create the DiscoveryClient: %v", err)
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.mammalsV1beta1 = mammalsv1beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.mammalsV1beta1 = mammalsv1beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
